api/Resources/config/providers.yml
I added the php binaries for all-inkl.com. They provide the following binariesin /usr/bin:
php (same as php56), php53, php54, php55, php56, php70, php71
=> add all-inkl.com to providers.yml

api/Resources/config/servers.yml
I suspect the AS number is for automatic lookup of the matching provider? If so, I added our own AS.
=> Add ETES to the list of known hosting providers

.gitattributes
When developing on Windows, the linter is going crazy about line endings, if core.autocrlf is on. The settings in .gitattributes force unix-style line endings on files that are subject to linting.
=> update .gitattributes to force lf line endings in *.js and *.vue

api/TaskOperation/Composer/CreateProjectOperation.php
Der PR ersetzt `file_get_contents` durch `Composer\Util\RemoteFilesystem::getContents`. Dadurch werden auch die Proxy-Einstellungen (genauer gesagt `$_SERVER['CGI_HTTP_PROXY']`) berücksichtigt, siehe #310, und Contao kann hinter dem Proxy installiert werden.
=> Switch to composer remote filesystem

src/components/fragments/Navigation.vue
As discussed [in the last call](https://github.com/contao/contao/issues/245#issuecomment-449027444), we want the links from the back end to the Contao Manager and from the Contao Manager to the back end to open in the same window. People can still open links without `target="_blank"` in new tabs if they want, but they cannot open links with `target="_blank"` in the same tab if they want.
=> Remove target="_blank" from the back end links

api/Resources/config/servers.yml
Add the parameter memory_limit=-1 to ETES hosting providers configuration.
=> Add parameter to ETES hosting providers configuration

api/Resources/config/servers.yml
Because we are no longer using vhost.io.
=> Update the Hostingwerk server domain

api/Resources/config/servers.yml
This PR disables the memory limit on cyon webhostings. Otherwise a default limit of 2 GB is applied, which might not be sufficient.
=> Disable memory limit for cyon webhosting

api/Resources/config/servers.yml
Wie in #538 beschreiben gibt es zusätzliche Pfade unter denen PHP-Binaries gefunden werden können. 
Dieses PR beinhaltet die nötige Anpassung.
=> PHP-Binary Pfade für Timme Hosting aktualisiert. Closes #538

api/Resources/i18n/en.yml
As discussed in the Mumble call on May 7th, Contao does not need `proc_open`.
=> Fix the proc_open explanation

vue.config.js
Webpack fails due to loader only checking for forward slashes in in tests. These fail on Windows systems, hence images could not be loaded. 
Also, the options in the webmanifest and browserconfig related file loader are uneccesary and seem to be there due to copy pasting (see https://www.npmjs.com/package/app-manifest-loader).
=> Update webpack loader config to work with windows directory separators as well

api/Controller/Server/ContaoController.php
The .ddev directory is a config for ddev. Just skip it.
[https://ddev.readthedocs.io/en/stable/users/topics/whats_in_ddev_dir/](https://ddev.readthedocs.io/en/stable/users/topics/whats_in_ddev_dir/)
=> Skip .ddev config

yarn.lock
This was probably overlooked in 3e3244721891a5887d9d2ecfbdc2f72f0daea43e
Without it being updated the build fails with the following error:
```
This dependency was not found:
* contao-package-list/src/i18n/sv.json in ./src/i18n/index.js
```
=> Fix outdated contao-package-list

vue.config.js
Using the hostname localhost seems to have issues.
But I’m not sure if maybe something with my setup is wrong?
The error I get without this change:
```
Proxy error: Could not proxy request /api.php/api/session from localhost:8081 to http://localhost:8000/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```
=> Fix could not proxy request error

package.json, yarn.lock
`node-sass` is deprecated (<https://sass-lang.com/blog/libsass-is-deprecated>) and cannot be installed on my architecture 😭
Switching to the recommended `sass` package seems to work fine, everything still looks correct (to me)
=> Replace node-sass with sass

.gitignore, build.xml.dist, composer.json, composer.lock, docs/build-phar.md, tools/phing/composer.json, tools/phing/composer.lock
As we use `bamarni/composer-bin-plugin` in most other Contao repositories, this would make sense here too IMO.
Benefits:
1. Simpler dev setup (as there is no need to install two extra dependencies globally)
2. All devs now get the same version of Box and Phing
=> Install Phing and Box using the Composer bin plugin

vue.config.js
Fixes the following warning:
```
WARN  "baseUrl" option in vue.config.js is deprecated now, please use "publicPath" instead.
```
=> Fix vue warning

api/Controller/Server/DatabaseController.php
Currently IP adresses weren’t allowed.
Like: `mysql://root:pwd@127.0.0.1:3306/db`
=> Fix database URL pattern

api/System/SelfUpdate.php
During self-update on windows the manager can no longer rename the file.
I took a closer look, the problem is that the self-update wants to "update" the phar.php via rename. This does not work correctly under Windows. So I thought to myself, that can't be that it works for composer and not for the manager :wink: And look, composer had the problem too ... and switched to copy for Windows https://github.com/composer/composer/commit/07f59a91624611b3c91477d2a1e6f6a2ce45aa5e#diff-b94d538399979b0c8d2689da7[...]6df384993c58e2e924c640dea1R428
This PR will fix the issue for Windows.
Perhaps the downgrade process needs some attention as well, possibly other places
https://github.com/contao/contao-manager/blob/main/downgrade.php#L36
=> use copy and unlink for Windows OS

api/Task/Packages/UpdateTask.php
Potential fix for #744. The reason why these people end up with `contao-setup` in their `composer.json` is likely because a version constraint of `>4.13.9999` also matches with `4.13.*` (e.g. `4.13.99991`) - but the intention was to only match Contao 5. This PR fixes that by changing the constraint to `>=5@dev`.
=> Fix version constraint for contao-setup script change

api/Controller/Contao/DatabaseMigrationController.php, docs/api/swagger.yaml, src/components/views/MigrationView.vue
Adds the error message to the migration view output as currently there is no way to know what went wrong when a schema migration fails.
=> Show error message in migration view

src/components/routes/Packages/BasePackage.vue
This PR fixes the uneven top and bottom gaps for the .package__details element.
Before:
After:
=> Align package details vertically centered

api/Command/AboutCommand.php, api/Command/IntegrityCheckCommand.php, api/Command/ProcessRunnerCommand.php, api/Command/TaskAbortCommand.php, api/Command/TaskDeleteCommand.php, api/Command/TaskUpdateCommand.php, api/Command/UpdateCommand.php
* Fixes #817
* Also uses return Constants for better readability
see:
https://tldp.org/LDP/abs/html/exitcodes.html
* `Command::SUCCESS = 0;`
* `Command::FAILURE = 1;`
* `Command::INVALID = 2;`
They exist in symfony/console 5.4 and still exist in 7.2
5.4:
https://github.com/symfony/console/blob/6473d441a913cb997123b59ff2dbe3d1cf9e11ba/Command/Command.php#L35-L38
7.2:
https://github.com/symfony/console/blob/b71a095124de660d598da3031c39e2790f64e28a/Command/Command.php#L37-L40
=> Add an AboutCommand return code

api/Controller/TaskController.php
A `DELETE` request to a resource should be idempotent. Meaning that it should return the same response, no matter how many times I call it. 
Calling `DELETE` means I want to delete the current task. If it's already been deleted, that's okay too 😊
=> Return a successful response if task already deleted

src/components/views/ConfigView.vue
Probably shouldn't be commented out. Without this it will get stuck like this:
=> Uncomment window.location.reload in ConfigView when updating config

src/components/routes/MaintenanceRoute.vue
This PR fixes a layout shift on the maintenance page caused by the Symfony logo being taller than wide and thus causing the parent to grow vertically. This obviously causes all the content below to shift as soon as the image has loaded.
With this change the Symfony logo is displayed slightly smaller, but all rows have the same height and there is no layout shift.
Before:
After:
=> Fix layout shift on maintenance page

src/components/routes/MaintenanceRoute.vue
Safari said no to the introduced aspect-ratio in #865.
Moving it to the `img` element should fix the following behavior:
=> Move `aspect-ratio` to the img element

src/components/routes/LogViewerRoute.vue
* fixes #871 
`$set` has been removed in Vue3 - we can set it properly now.
*Additional information*
- `^= 1` is a bitwise XOR so it assigns the negated state :) (m-vo taught me :D)
=> Correctly toggle `context` and `extra` in the LogViewer
